# Generated by Django 3.1.2 on 2020-10-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('id_cite', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(verbose_name='Date creation')),
                ('update_date', models.DateTimeField(verbose_name='Date  update')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('code_country', models.CharField(max_length=20)),
                ('creation_date', models.DateField()),
                ('Modification_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateField()),
                ('Modification_date', models.DateField()),
            ],
        ),
    ]
